/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ChatIdRouteImport } from './routes/$chatId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat/stream'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIdRoute = ChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat/stream',
  path: '/api/chat/stream',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$chatId': typeof ChatIdRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$chatId': typeof ChatIdRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$chatId': typeof ChatIdRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$chatId'
    | '/settings'
    | '/sign-in'
    | '/api/chat/stream'
    | '/api/trpc/$'
    | '/api/webhooks/clerk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$chatId'
    | '/settings'
    | '/sign-in'
    | '/api/chat/stream'
    | '/api/trpc/$'
    | '/api/webhooks/clerk'
  id:
    | '__root__'
    | '/'
    | '/$chatId'
    | '/settings'
    | '/sign-in'
    | '/api/chat/stream'
    | '/api/trpc/$'
    | '/api/webhooks/clerk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatIdRoute: typeof ChatIdRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$chatId': {
      id: '/$chatId'
      path: '/$chatId'
      fullPath: '/$chatId'
      preLoaderRoute: typeof ChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/stream': {
      id: '/api/chat/stream'
      path: '/api/chat/stream'
      fullPath: '/api/chat/stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatIdRoute: ChatIdRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
